### ISSUE TITLE
Errors while executing the examples

### ISSUE THREAD

**Issue by mikelalda** [sedelpeuch/ronoco#4]
**Describe the bug**
Hi!! I am trying to run ronoco in noetic-devel. First of all, I have to say that I moved the launcher file from ronoco-vm/tests to ronoco-vm not to have any error. 

Everything works well until I run the launcher.py. I get AssertionError while testing, its different in each robot, kuka gave me error in test_cartesianpoint. UR gave me the error in test_control. see the errors below.
```bash
======================================================================
FAIL: test_play (tests.test_control.TestControl)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mikel/donbosco_ws/src/ronoco/ronoco-vm/tests/test_control.py", line 129, in test_play
    self.assertEqual(200, response.status_code)
AssertionError: 200 != 500

======================================================================
FAIL: test_add_point_simulation (tests.test_cartesianpoint.TestCartesian)
Test route "/point/add/simulation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mikel/donbosco_ws/src/ronoco/ronoco-vm/tests/test_cartesianpoint.py", line 66, in test_add_point_simulation
    self.assertEqual(result.status_code, 200)
AssertionError: 408 != 200
```
Another thing to comment is that when I click the run button, the terminal gives an error like this.

```bash
Error [429b1c3bc57faf07] Service not found
```

I don't know if it is because I have different name of services or it is something else. How could I know which are the services that the ui is loking for?

**To Reproduce**
I have followed the procesure of the [UR](https://sdelpeuch.github.io/ronoco/v2.x/user-guides/ur3.html) and [KUKA](https://sdelpeuch.github.io/ronoco/v2.x/user-guides/kuka.html) robots, but both seem to fail.

Thanks!

**Comment by sedelpeuch** [comment]
Hello,

Firstly, it is strange to have to move the test launcher and the errors caused by the tests are not normal, they must have occurred between the passage of v1 and v2. In any case the failures of these tests should not prevent you from using the application. 

To see more information about the service problem you can directly look at the ronoco-vm console, the errors given by Flask will be more telling. It looks like a service naming problem between your robot and mine, instinctively I'll say it's around the compliant service, 
What is the behavior tree you implemented to get this error? The problem can also come from the incorrect use of a service block. 

Thanks for taking the time to test!

Sincerely,

Sébastien Delpeuch
